project/instagif/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "instagif"
urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', views.admin_home, name="admin_home"),
    path('admin/<str:menu>/', views.admin, name="admin"),
    path('admin/user/edit/<int:id>/', views.admin_user_edit, name="admin_user_edit"),
    path('admin/user/delete/<int:id>/', views.admin_user_delete, name="admin_user_delete"),
    path('admin/user/create/', views.admin_user_create, name="admin_user_create"),
    path('admin/tag/edit/<int:id>/', views.admin_tag_edit, name="admin_tag_edit"),
    path('admin/tag/delete/<int:id>/', views.admin_tag_delete, name="admin_tag_delete"),
    path('admin/tag/create/', views.admin_tag_create, name="admin_tag_create"),
    path('admin/image/create/', views.admin_image_create, name="admin_image_create"),
    path('admin/image/edit/<uuid:id>/', views.admin_image_edit, name="admin_image_edit"),
    path('admin/image/delete/<uuid:id>/', views.admin_image_delete, name="admin_image_delete"),
    path('search/tag/<str:tag_name>/', views.search_tag, name="search_tag"),
    path('search/', views.search, name="search"),
    path('detail/<str:id>', views.detail, name="detail"),
    path('detail/user/<int:id>/', views.user_detail, name="user_detail"),
    path('reel/all/', views.reel_all, name="reel_all"),
    # path('reel/<int:user_id>/', views.reel, name="reel"),
    path('reel/<int:user_id>/', views.reel_all, name="reel"),
    path("login/", views.login_page, name="login"),
    path("signup/", views.signup_page, name="signup"),
    path("logout/", views.api_logout, name="logout"),
    path("like/<uuid:image_id>/", views.api_like, name="like"),
    path("save/<uuid:image_id>/", views.api_save, name="save"),
    path("comment/", views.api_comment, name="comment"),
    path("follow/<int:following_id>/", views.api_follow, name="follow" ),
    path("profile/", views.profile, name="profile"),
    path("profile/edit/", views.api_edit_profile, name="edit_profile"),
    path("upload/", views.upload, name="upload"),
    path("download/<str:image_id>/", views.download, name="download"),
    


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instagif/', include('instagif.urls', 'instagif'))
]

project/instagif/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import uuid
from PIL import Image as PIL_Image
from io import BytesIO
from django.core.files import File
import os


MEDIA_FOLDER_AVATAR = "instagif/avatar/"
MEDIA_FOLDER_IMAGE = "instagif/image/"

def resize_image(image, size=(128, 128)):
    pil_image = PIL_Image.open(image)
    name, ext = os.path.splitext(image.path)
    ext = ext[1:].upper()
    if ext == "JPG":
        ext = "JPEG"
    pil_image = pil_image.convert("RGB")
    if size is not None:
        pil_image.thumbnail(size, PIL_Image.ANTIALIAS)
    pil_io = BytesIO()
    pil_image.save(pil_io, format='JPEG', quality=50)
    pil_file = File(pil_io, name=image.name)
    return pil_file


class CustomUser:
    None




class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    name = models.CharField(max_length=100, null=True)
    avatar = models.ImageField(upload_to=MEDIA_FOLDER_AVATAR)
    is_admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def trimmed_name(self, len=12):
        if len(self.name) > len:
            return self.name[:len] + "..."
        else:
            return self.name

    def save(self, *args, **kwargs):
        self.avatar = resize_image(self.avatar, size=(128,128))
        super().save(*args, **kwargs)

        


class Following(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=MEDIA_FOLDER_IMAGE)
    thumbnail = models.ImageField(upload_to=MEDIA_FOLDER_IMAGE, default=None, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField(default="No description yet...")
    like_count = models.IntegerField(default=0)
    save_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def description_short(self, len=100):
        if len(self.description) > len:
            return {
                "show_more": True,
                "short": self.description[:len],
                "long": self.description[len:],
            }
        else:
            return {
                "show_more": False,
                "short": self.description[:len],
                "long": self.description[len:],
            }


    def save(self, *args, **kwargs):
        self.thumbnail = resize_image(self.image, size=(360, 360))
        super().save(*args, **kwargs)



class LikedImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class SavedImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class CommentImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE) 
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_trimmed_content(self, limit=50):
       return self.content[:limit]


class Tag(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class TagImage(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

project/instagif/views.py
from ast import Bytes
import re
from django.http.response import JsonResponse, FileResponse
from django.shortcuts import redirect, render
from django.http import request, HttpResponse
from django.template.loader import render_to_string
from django.template import Template, Context
from django.template.engine import Engine
from django.urls import reverse
from pprint import pprint, pformat
from .business_logic import str_to_bool, get_mini_comments_from_querysets, get_user
from .decorators import is_admin
from django.contrib.auth.models import User
from django.db.models import Count
from django.db import connection
from django.contrib.auth import authenticate, update_session_auth_hash, login, logout
from django.core.files import File
from django.core.files.base import ContentFile
from django.core.files.uploadedfile import InMemoryUploadedFile
from .models import Following, Person, Image, LikedImage, SavedImage, CommentImage, Tag, TagImage
from datetime import datetime
import json
import base64
from io import BytesIO, StringIO
from PIL import Image as PIL_Image


# Create your views here.
@is_admin
def admin_home(request):
    return redirect("instagif:admin", menu="users")

@is_admin
def admin(request, menu):
    limit = 10
    page = request.GET.get("page", 1)
    offset = (page - 1)*limit                         # 10 items per page
    if menu == "users":
        persons = Person.objects.all()[offset:(limit + offset)]
        items = []
        for person in persons:
            items.append({
                "id": person.user.id,
                "username": person.name,
                "email": person.email,
                "avatar": person.avatar.url,
            })
        template = "admin_users.html"
    elif menu == "images":
        items = Image.objects.all()[offset:(limit + offset)]
        template = "admin_images.html"
    elif menu == "tags":
        items = Tag.objects.all()[offset:(limit + offset)]
        template = "admin_tags.html"
    else:
        return HttpResponse("ERROR: Page not found.")

    return render(request, ("instagif/" + template), context={"items": items, "menu": menu})

@is_admin
def admin_user_edit(request, id):
    if request.method == "GET":
        user = get_user(request, id=id)
        return render(request, "instagif/admin_user_edit.html", context={"user": user})

    elif request.method == "POST":
        if request.is_ajax():
            user = User.objects.get(id=id)
            person = Person.objects.get(user_id=id)
            username = request.POST["username"]
            email = request.POST["email"]
            password_checkbox = request.POST["password_checkbox"]
            password = request.POST["password"]
            password_confirm = request.POST["password_confirm"]

            if password_checkbox:
                if password == password_confirm:
                    user.set_password(password)
                else:
                    return JsonResponse({
                        "status": "ERROR",
                        "message": "Password inputs don't match!"
                    })

            user.first_name = username
            user.username = email
            person.name = username
            person.email = email
            if "avatar" in request.FILES:
                avatar = request.FILES["avatar"]
                person.avatar = avatar
            user.save()
            person.save()

            return JsonResponse({
                "status": "Ok",
                "message": "Profile has been edited successfully."
            })

        else:
            return HttpResponse("ERROR: Request must be made with ajax!")
    else:
        return HttpResponse("ERROR: Forbidden method.")

@is_admin
def admin_user_create(request):
    if request.method == "GET":
        return render(request, "instagif/admin_user_create.html")

    elif request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        avatar = request.FILES["avatar"]
        password = request.POST["password"]
        password_confirm = request.POST["password_confirm"]

        if password == password_confirm:
            user = User.objects.create_user(username=email, first_name=username, password=password)
            person = Person(user=user, name=username, email=email, avatar=avatar)
            person.save()
            return JsonResponse({
                "status": "Ok",
                "message": "Profile has been edited successfully."
            })
        else:
            return JsonResponse({
                "status": "ERROR",
                "message": "Password inputs don't match!"
            })
    else:
        return HttpResponse("ERROR: Forbidden method.")

@is_admin
def admin_user_delete(request, id):
    if request.method == "DELETE":
        current_user_id = request.user.id
        if current_user_id == id:
            print("error del self")
            return JsonResponse({
                "status": "ERROR",
                "message": "Cannot delete yourself like this :("
            })

        user = User.objects.get(id=id)
        user.delete()
        print("success")
        return JsonResponse({
            "status": "Ok",
            "message": "User ID: " + str(user.id) + " has been deleted sucessfully."
        })
    
    else:
        return HttpResponse("ERROR: Forbidden method.")

@is_admin
def admin_tag_edit(request, id):
    if request.method == "GET":
        tag = Tag.objects.get(id=id)
        tag_dict = {
            "id": tag.id,
            "name": tag.name
        }
        return render(request, "instagif/admin_tag_edit.html", context={"tag": tag_dict})

    elif request.method == "POST":
        tag = Tag.objects.get(id=id)
        name = request.POST["name"]                         # encoded data is always in POST dict
        tag.name = name
        tag.save()
        return JsonResponse({
            "status": "Ok",
            "message": "Tag has been updated successfully."
        })

@is_admin
def admin_tag_create(request):
    if request.method == "GET":
        return render(request, "instagif/admin_tag_create.html")
    elif request.method == "POST":
        name = request.POST["name"]
        tag = Tag(name=name)
        tag.save()
        return JsonResponse({
            "status": "Ok",
            "message": "Tag has been created successfully."
        })

@is_admin
def admin_tag_delete(request, id):
    if request.method == "DELETE":
        tag = Tag.objects.get(id=id)
        tag.delete()

        return JsonResponse({
            "status": "Ok",
            "message": "Tag has been deleted successfully."
        })
    else:
        return HttpResponse("ERROR: Forbidden method.")

@is_admin
def admin_image_create(request):
    if request.method == "GET":
        tags = Tag.objects.all()
        users = User.objects.all()

        return render(request, "instagif/admin_image_create.html", context={"tags": tags, "users": users})
    elif request.method == "POST":
        user_id = request.POST["user_id"]
        image = request.FILES["image"]
        title = request.POST["title"]
        tags_str = request.POST["tags_str"]
        tags_split = tags_str.split("-")
        tags_list = []
        for tag_val in tags_split:
            tags_list.append(int(tag_val))        

        new_image = Image(user_id=user_id, image=image, title=title)
        new_image.save()

        for tag in tags_list:
            tag_image = TagImage(tag_id=tag, image=new_image)
            tag_image.save()

        return JsonResponse({
            "status": "Ok",
            "message": "Image has been created successfully."
        })
    else:
        return JsonResponse({
            "status": "ERROR",
            "message": "Forbidden method."
        })

@is_admin
def admin_image_edit(request, id):
    if request.method == "GET":
        image_obj = Image.objects.get(id=id)
        users = User.objects.all()
        tags_obj = Tag.objects.all()
        tags_images = TagImage.objects.filter(image=image_obj)
        tags_images_list = []
        for tag_image in tags_images:
            tags_images_list.append(tag_image.tag_id)
        tags = []
        for tag in tags_obj:
            if tag.id in tags_images_list:
                tags.append({"id": tag.id,
                "name": tag.name,
                "selected": True})
            else:
                tags.append({"id": tag.id,
                "name": tag.name,
                "selected": False})

        return render(request, "instagif/admin_image_edit.html", context={
            "image" : image_obj, 
            "users": users, 
            "tags": tags, 
            "tags_images_list": tags_images_list
            })

    elif request.method == "POST":
        image_obj = Image.objects.get(id=id)
        title = request.POST["title"]
        user_id = request.POST["user_id"]
        
        tags_str = request.POST["tags_str"]
        tags_split = tags_str.split("-")
        tags_list = []
        for tag_val in tags_split:
            tags_list.append(int(tag_val))     

        image_obj.title = title
        image_obj.user_id = user_id
        if "image" in request.FILES:
            image = request.FILES["image"]
            image_obj.image = image
        image_obj.save()

        TagImage.objects.filter(image_id=id).delete()           # delete old tag_images
        for tag in tags_list:
            tag_image = TagImage(tag_id=tag, image=image_obj)
            tag_image.save()

        return JsonResponse({
            "status": "Ok",
            "message": "Image has been updated successfully."
        })
    else:
        return JsonResponse({
            "status": "ERROR",
            "message": "Forbidden method."
        }) 

@is_admin
def admin_image_delete(request, id):
    if request.method == "DELETE":
        image = Image.objects.get(id=id)
        image.delete()
        return JsonResponse({

project/instagif/templates/instagif/admin_images.html
{% extends "instagif/admin.html" %}



{% block content %}
{% csrf_token %}

<div id="add-container">
    <a id="add-link" class="btn btn-success" href="{% url 'instagif:admin_image_create' %}">Add Image</a>
</div>


<table id="main-table" class="table">
    <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">ID</th>
            <th scope="col">Title</th>
            <th scope="col">Image</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>

    <tbody>
    {% for item in items %}
        <tr id="row-{{ item.id }}">
            <td>{{ forloop.counter }}</td>
            <td>{{ item.id }}</td>
            <td>{{ item.title }}</td>
            <td>
                <img class="row-image" src="{{ item.image.url }}">
            </td>
            <td>
                <a href="{% url 'instagif:admin_image_edit' item.id %}" type="button" class="btn btn-primary">Edit</a>
                <button id="image__{{ item.id }}" type="button" class="delete-button btn btn-danger">Delete</button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

project/instagif/templates/instagif/admin_tags.html
{% extends "instagif/admin.html" %}



{% block content %}
{% csrf_token %}

<div id="add-container">
    <a id="add-link" class="btn btn-success" href="{% url 'instagif:admin_tag_create' %}">Add Tag</a>
</div>


<table id="main-table" class="table">
    <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>

    <tbody>
    {% for item in items %}
        <tr id="row-{{ item.id }}">
            <td>{{ forloop.counter }}</td>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}</td>
            <td>
                <a href="{% url 'instagif:admin_tag_edit' item.id %}" type="button" class="btn btn-primary">Edit</a>
                <button id="tag-{{ item.id }}" type="button" class="delete-button btn btn-danger">Delete</button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

project/instagif/templates/instagif/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagif - index</title>
</head>
<body>

    {% load static %}

    
    <div id="super-container">
        <div id="top-bar-container">
            <div id="top-bar">
                <a id="logo" class="top-bar-item" href="{% url 'instagif:index' %}" >Instameme</a>
                <div id="search" class="top-bar-item">
                    <div id="search-input-container">
                        <input type="text" id="search-input" value="{{ query }}" placeholder="Search..." >
                        <a id="search-button" href="https://en.wikipedia.org">
                            <img src="{% static 'instagif/search.png' %}" alt="search img" class="top-bar-item-img">
                        </a>
                    </div>

                    <div id="small-search-input-container">
                        <button id="small-search-button">
                            <img src="{% static 'instagif/search.png' %}" alt="small search img" class="top-bar-item-img">
                        </button>
                    </div>

                    <div id="small-search-input-popup-container" class="small-search-popup-inactive">
                        <button id="cancel-button">
                            <img src="{% static 'instagif/cancel.png' %}" alt="cancel image" id="cancel-img">
                        </button>
                        <div id="small-search-input-popup-button-container">
                            <input type="text" id="small-search-input" value="{{ query }}" placeholder="Search..." >
                            <a id="small-search-button-popup" href="#">
                                <img src="{% static 'instagif/search.png' %}" alt="" class="top-bar-item-img">
                            </a>
                        </div>
                    </div>
                </div>

                <div id="add-account-container">
                    {% if request.user.is_authenticated %}
                    <div id="add">
                        <a id="add-link" href="{% url 'instagif:upload' %}">
                            <button id="add-button">
                                <img src="{% static 'instagif/upload.png' %}" alt="" class="top-bar-item-img">
                            </button>
                        </a>
                    </div>
                    {% endif %}


                    <div id="account" class="top-bar-item">

                        <button id="account-button" class="top-bar-item-button">
                            {% if request.user.is_authenticated %}
                            <img src="{{ request.user.person.avatar.url }}" alt="avatar" id="avatar" class="top-bar-item-img border-radius-50">
                            {% else %}
                            <img src="{% static 'instagif/account.png' %}" id="avatar" alt="avatar" class="top-bar-item-img">
                            {% endif %}
                        </button>
                        
                        <div id="account-dropdown" class="account-active-background display-none">
                            <div id="account-dropdown-triangle"></div>
                            {% if request.user.is_authenticated %}

                            {% if request.user.person.is_admin == True %}
                            <a href="{% url 'instagif:admin_home' %}" id="account-profile" class="account-dropdown-item-link">
                                <img src="{% static 'instagif/hacker.png' %}" alt="" class="account-dropdown-item-img">
                                <p class="account-dropdown-item-text">Admin</p>
                            </a>
                            {% endif %}

                            <a href="{% url 'instagif:profile' %}#profile" id="account-profile" class="account-dropdown-item-link">
                                <img src="{% static 'instagif/account.png' %}" alt="" class="account-dropdown-item-img">
                                <p class="account-dropdown-item-text">Profile</p>
                            </a>
                            <a href="{% url 'instagif:profile' %}#saved-images" class="account-dropdown-item-link">
                                <img src="{% static 'instagif/unsaved.png' %}" alt="" class="account-dropdown-item-img">
                                <p class="account-dropdown-item-text">Saved Images</p>
                            </a>
                            <hr class="account-dropdown-line">
                            <form id="logout-form" action="{% url 'instagif:logout' %}" method="POST">
                                {% csrf_token %}
                                <button id="logout-button" class="account-dropdown-item-link" type="submit">
                                    <img src="{% static 'instagif/logout.png' %}" alt="" class="account-dropdown-item-img">
                                    <p class="account-dropdown-item-text">Log out</p>
                                </button>
                            </form>
                            {% else %}
                            <a href="{% url 'instagif:login' %}" id="account-login" class="account-dropdown-item-link">
                                <img src="{% static 'instagif/account.png' %}" alt="" class="account-dropdown-item-img">
                                <p class="account-dropdown-item-text">Log in</p>
                            </a>
                            <a href="{% url 'instagif:signup' %}" id="account-login" class="account-dropdown-item-link">
                                <img src="{% static 'instagif/account.png' %}" alt="" class="account-dropdown-item-img">
                                <p class="account-dropdown-item-text">Sign up</p>
                            </a>
                            {% endif %}
                        </div>
                        



                    </div>
                </div>
            </div>
        </div>

        <div id="overlay" class="overlay-inactive"></div>

        <div id="base-content-container">
            <!-- Content -->
            {% block content %}
            <h2>No content available, or an error occured :(</h2>
            {% endblock %}
        </div>
    
    


        <!-- Attributions-->
        {% block footer %}
        <!-- <footer id="footer">
            <div id="footer-about" class="footer-item">
                <a href="#">About</a>
            </div>
            <div id="footer-contact" class="footer-item">
                <a href="#">Contact</a>
            </div>
            <div id="footer-attributions" class="footer-item">
                <a href="#">Attributions</a>
            </div>
        </footer> -->
        {% endblock %}
    
    
    </div>




    <!-- Style -->
    <link rel="stylesheet" href="{% static 'instagif/base.css' %}">
    <script src="{% static 'instagif/base.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Lobster&family=Montserrat:wght@300&family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
    <link href="https://vjs.zencdn.net/7.17.0/video-js.css" rel="stylesheet" />
    <!-- <script src="https://vjs.zencdn.net/7.17.0/video.min.js"></script> -->
    {% block style %}
    {% endblock %}



    



</body>
</html>

project/instagif/templates/instagif/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Master Page</title>
</head>
<body>
    {% load static %}
    <div id="super-container">
        <div id="top-bar-container">
            <div id="top-bar">
                <a id="logo" class="top-bar-item" href="{% url 'instagif:index' %}" >Instagif</a>
                <div id="search" class="top-bar-item">
                    <div id="search-input-container">
                        <input type="text" id="search-input" value="{{ query }}" >
                        <a id="search-button" href="https://en.wikipedia.org">
                            <img src="{% static 'instagif/search.png' %}" alt="" class="top-bar-item-img">
                        </a>
                    </div>
                </div>
                <div id="account" class="top-bar-item">
                    <button id="account-button" class="top-bar-item-button">
                        <img src="{% static 'instagif/account.png' %}" alt="avatar" class="top-bar-item-img">
                    </button>
                    
                    <div id="account-dropdown" class="account-active-background display-none">
                        {% if person %}
                        <a href="#" id="account-profile" class="account-dropdown-item-link">
                            <img src="{% static 'instagif/account.png' %}" alt="" class="account-dropdown-item-img">
                            <p class="account-dropdown-item-text">Profile</p>
                        </a>
                        <a href="#" class="account-dropdown-item-link">
                            <img src="{% static 'instagif/account.png' %}" alt="" class="account-dropdown-item-img">
                            <p class="account-dropdown-item-text">Saved Gifs</p>
                        </a>
                        <hr class="account-dropdown-line">
                        <form id="logout-form" action="{% url 'instagif:logout' %}" method="POST">
                            {% csrf_token %}
                            <button id="logout-button" class="account-dropdown-item-link" type="submit">
                                <img src="{% static 'instagif/account.png' %}" alt="" class="account-dropdown-item-img">
                                <p class="account-dropdown-item-text">Log out</p>
                            </button>
                        </form>
                        {% else %}
                        <a href="{% url 'instagif:login' %}" id="account-login" class="account-dropdown-item-link">
                            <img src="{% static 'instagif/account.png' %}" alt="" class="account-dropdown-item-img">
                            <p class="account-dropdown-item-text">Log in</p>
                        </a>
                        {% endif %}
                    </div>
                    



                </div>
            </div>
        </div>

        {% csrf_token %}
        <div id="master-content-container">
            <!-- content start
            content end -->

        </div>
        
    </div>



    <input type="hidden" id="init-url" value="{{ init_url }}">
    <link rel="stylesheet" href="{% static 'instagif/base.css' %}">
    <link rel="stylesheet" href="{% static 'instagif/master.css' %}">
    <script src="{% static 'instagif/master.js' %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Lobster&family=Montserrat:wght@300&family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
    <link href="https://vjs.zencdn.net/7.17.0/video-js.css" rel="stylesheet" />
    <script src="https://vjs.zencdn.net/7.17.0/video.min.js"></script>


</body>
</html>

project/instagif/templates/instagif/search.html
{% extends "instagif/base.html" %}

{% block content %}

{% load static %}
<div id="search-result-text">
    Search results for <span id="search-text">"{{ query }}"</span>
</div>
<div id="search-container">

    {% for image in images %}

    <div class="search-item">
        <a class="search-item-button" href="{% url 'instagif:detail' image.id %}">
            <img class="search-item-img" src="{{ image.src }}" >
            <!-- <video class="search-item-img" autoplay muted loop>
                <source src="{{ item.gif_url }}" type="video/mp4">
                <source src="{{ item.gif_url }}" type="video/gif">
                Your browser does not support the video tag.
            </video>      -->
        </a>
    </div>
    
    {% endfor %}



</div>
{% endblock %}


{% block style %}
<link rel="stylesheet" href="{% static 'instagif/search.css' %}">
{% endblock %}